apiVersion: v1
kind: Service
metadata:
  name: backend-v1
spec:
  type: NodePort
  selector:
    app: backend   # 🔥 IMPORTANT (no version)
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007