name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Docker Running
        run: docker ps

      - name: Build Docker Image
        working-directory: backend
        run: docker build -t cicd-backend .

      - name: Ensure Minikube Running
        run: |
          minikube status || minikube start

      - name: Load Image into Minikube
        run: minikube image load cicd-backend

      - name: Restart Kubernetes Deployment
        run: kubectl rollout restart deployment backend-v1

      - name: Verify Deployment
        run: kubectl get pods

      - name: Use Secrets (Debug Step)
        run: echo "Using secure credentials"
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}